# Generated by Django 6.0 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrador'),
                    ('supervisor', 'Supervisor'),
                    ('empleado', 'Empleado'),
                    ('cliente', 'Cliente'),
                ],
                default='empleado',
                max_length=20,
            ),
        ),
    ]
