# Generated by Django 6.0 on 2026-02-19 00:00

from django.conf import settings
from django.db import migrations


ROLE_GROUP_MAP = {
    'admin': 'Rol Administrador',
    'supervisor': 'Rol Supervisor',
    'empleado': 'Rol Empleado',
    'cliente': 'Rol Cliente',
}

MANAGED_APPS = {'tablero', 'lista', 'ticket', 'comentario', 'etiqueta', 'usuario'}

ROLE_PERMISSIONS = {
    'supervisor': {
        ('tablero', 'add_tablero'),
        ('tablero', 'change_tablero'),
        ('tablero', 'delete_tablero'),
        ('tablero', 'view_tablero'),
        ('lista', 'add_lista'),
        ('lista', 'change_lista'),
        ('lista', 'delete_lista'),
        ('lista', 'view_lista'),
        ('ticket', 'add_ticket'),
        ('ticket', 'change_ticket'),
        ('ticket', 'delete_ticket'),
        ('ticket', 'view_ticket'),
        ('comentario', 'add_comentario'),
        ('comentario', 'change_comentario'),
        ('comentario', 'delete_comentario'),
        ('comentario', 'view_comentario'),
        ('etiqueta', 'add_etiqueta'),
        ('etiqueta', 'change_etiqueta'),
        ('etiqueta', 'delete_etiqueta'),
        ('etiqueta', 'view_etiqueta'),
        ('usuario', 'view_perfilusuario'),
        ('usuario', 'change_perfilusuario'),
    },
    'empleado': {
        ('tablero', 'view_tablero'),
        ('lista', 'view_lista'),
        ('ticket', 'add_ticket'),
        ('ticket', 'change_ticket'),
        ('ticket', 'view_ticket'),
        ('comentario', 'add_comentario'),
        ('comentario', 'change_comentario'),
        ('comentario', 'view_comentario'),
        ('etiqueta', 'view_etiqueta'),
    },
    'cliente': {
        ('tablero', 'view_tablero'),
        ('lista', 'view_lista'),
        ('ticket', 'view_ticket'),
        ('comentario', 'add_comentario'),
        ('comentario', 'view_comentario'),
        ('etiqueta', 'view_etiqueta'),
    },
}


def sync_group_permissions(Group, Permission, role):
    group, _ = Group.objects.get_or_create(name=ROLE_GROUP_MAP[role])
    if role == 'admin':
        permissions = Permission.objects.filter(content_type__app_label__in=MANAGED_APPS)
    else:
        permissions = Permission.objects.filter(
            content_type__app_label__in=[app for app, _ in ROLE_PERMISSIONS[role]],
            codename__in=[codename for _, codename in ROLE_PERMISSIONS[role]],
        )
    group.permissions.set(permissions)
    return group


def forward(apps, schema_editor):
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(auth_app_label, auth_model_name)
    PerfilUsuario = apps.get_model('usuario', 'PerfilUsuario')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups_by_role = {
        role: sync_group_permissions(Group, Permission, role)
        for role in ROLE_GROUP_MAP.keys()
    }
    role_groups = Group.objects.filter(name__in=ROLE_GROUP_MAP.values())

    for user in User.objects.all():
        default_role = 'admin' if getattr(user, 'is_superuser', False) else 'empleado'
        perfil, _ = PerfilUsuario.objects.get_or_create(user_id=user.pk, defaults={'rol': default_role})
        if getattr(user, 'is_superuser', False) and perfil.rol != 'admin':
            perfil.rol = 'admin'
            perfil.save(update_fields=['rol'])
        user.groups.remove(*role_groups)
        user.groups.add(groups_by_role[perfil.rol])


def backward(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
