# Generated by Django 6.0 on 2025-12-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0002_integrantetablero'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lista',
            unique_together={('tablero', 'orden')},
        ),
    ]
