# Generated by Django 6.0 on 2025-12-09 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_tickets', to='ticket.tag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Etiqueta aplicada al ticket',
                'verbose_name_plural': 'Etiquetas aplicadas a tickets',
                'unique_together': {('ticket', 'tag')},
            },
        ),
    ]
