# Generated by Django 6.0 on 2026-02-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablero', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#cccccc', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='tablero.tablero')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_tickets', to='etiqueta.etiqueta')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_etiquetas', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Etiqueta aplicada al ticket',
                'verbose_name_plural': 'Etiquetas aplicadas a tickets',
                'unique_together': {('ticket', 'etiqueta')},
            },
        ),
    ]
