# Generated by Django 6.0 on 2025-12-08 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegranteTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='tablero.tablero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_como_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrante del Tablero',
                'verbose_name_plural': 'Integrantes del Tablero',
                'unique_together': {('usuario', 'tablero')},
            },
        ),
    ]
